### PR TITLE
Adds overwrite memory err/warn, small changes in options and list file

### PR DESCRIPTION
**Pull request by wd5gnr**
Note that even if you don't want to incorporate the new error/warning for memory overwrite, you might consider that warnings and errors need a new line in the log file. Also, some trivial changes to option processing to make it slightly less inefficient. Finally, I noticed that compMode can be set to A or O but no where in the code is this set? Looks like a feature that never got finished maybe? I didn't remove anything, but did initialize the variable and put a comment to that effect in.

### CODE REVIEW

**Comment by wd5gnr** [comment]
Added improved option handling since I was in there. Help messages, much easier to add options. Options are more flexible (using getopt_long_only). So, this should all work now:
-D foo
-Dfoo
-Dfoo=bar
-D foo=bar

You can also shorten long options as long as they are unique. For example -elf is now the same as -elf2k because there is nothing else that starts with that. 

There was, by the way, a small bug in the existing option parsing where malloc was never called for storing strings.  It never showed up because the initial variable was init to NULL and when you call realloc with NULL it is the same as malloc. But if you elect to keep the old code that should either be fixed to call only realloc or to not increment the file name counter BEFORE testing to see if it is zero. Or something. Or just take this code and that's gone anyway.

**Comment by fourstix** [comment]
I'm having trouble with the code in this PR when assembling a file bad2.asm.  It's missing the op definitions include file
Under the current version in updates built as asm02.exe it fails as expected.  

Asm02>asm02 -l -binary -pev2 test.asm
Asm/02 v1.5
by Michael H. Riley
test.asm:49: *ERROR: Unknown opcode: RTN
   49 |         RTN                     ; return to Elf/OS
Errors during pass 1, aborting pass 2

Lines Assembled   : 336
Code Generated    : 0
Errors            : 1

But in the code in Al's PR branch, built in Windows as asm02_al.exe it fails silently.
Asm02>asm02_al -l -b -pev2 bad2.asm
Asm/02 v1.5
by Michael H. Riley

Asm02>
Here is the test file, with the .txt extension added so I can attach it to this comment.

[bad2.asm.txt](https://github.com/arhefner/Asm-02/files/12563543/bad2.asm.txt)

**Comment by wd5gnr** [comment]
Huh... I'll look at it.

**Comment by wd5gnr** [comment]
So does opcodes.def get read in by default, then? I missed that, I think

**Comment by wd5gnr** [comment]
So I see what you're saying. Well I get an error when I try it here. So I assume since you were saying it was wrong that it includes that file automatically, but in fact I do get an error. So I wonder if there's some difference in the way you're building under windows that is causing a problem. Can you confirm that what you're saying is it doesn't give you an error on my branch and you expect it to give you an error.

**Comment by fourstix** [comment]
Correct, on Windows it exits silently.  I think it's related to the fact the changes broke the build I maintain on Windows.   Windows Visual Studio Community edition does not have a getopts.h file.  I used one I found in GitHub.  There are also other differences how files are opened in Windows as well.  I'll open an issue on your repository so we can track it there.

**Comment by wd5gnr** [comment]
I had put an ifdef around it but then took it out. Let me see if I can
bring in a getopt. If not I'll roll that back so we been consider the
memory overlap separately.

**Comment by wd5gnr** [comment]
This is what I get:
alw@Enterprise:~/projects/embedded/1802/Asm-02$ ./asm02 -l -b -pev2 bad2.asm
Asm/02 v1.5
by Michael H. Riley
bad2.asm:15: *ERROR: Could not open 'bios.inc'
   15 | #include bios.inc
bad2.asm:16: *ERROR: Could not open 'kernel.inc'
   16 | #include kernel.inc
bad2.asm:49: *ERROR: Unknown opcode: RTN
   49 |         RTN                     ; return to Elf/OS
Errors during pass 1, aborting pass 2

Lines Assembled   : 65
Code Generated    : 0
Errors            : 3


However, I'm going to put an option in to locally host an open getopt replacement.

**Comment by wd5gnr** [comment]
Ok try this one. I added a 3rd-party getopt replacement. There is no good reason not to use in on all platforms, but removing the USE_YA_GETOP symbol will force the normal library on Linux. I needed to acknowledge the license for that, so I wrote a simple readme.md that basically has the info in asm.doc, some notes from me, and the licenses.

**Comment by fourstix** [comment]
Hi,
Thanks. I'll test it.  I created an issue https://github.com/wd5gnr/Asm-02/issues/1  so we can track it.

**Comment by fourstix** [comment]
We tracked this issue all the way back to a problem in my installation of Visual Studio 2019.  Upgrading to VS 2022 fixed the issue.  Many thanks, to @wd5gnr  for his patience and help.

**Comment by wd5gnr** [comment]
Sorry I botched two spots in the readme formatting. Will fix.

**Pull request merged**
